### ISSUE TITLE
gem install failure due to dependency rugged-0.21.4 and libgit2 cause link failed when using system http_parser

### ISSUE THREAD

**Issue by PetrusZ** [patrickdavey/vimwiki_markdown#13]
Detail please see libgit2/libgit2#4336 and it's already fixed at last year libgit2/libgit2/pull/4339.

The dependency need to update or using another way to install vimiwki_markdown.

**Comment by PetrusZ** [comment]
BTW, use rvm install success, but have some error when convert markdown to html, sorry I'm not record that. Have been uninstalled for now.

**Comment by PetrusZ** [comment]
```
Error detected while processing function vimwiki#html#Wiki2HTML[1]..<SNR>205_convert_file[15]..vimwiki#html#CustomWiki2HTML[2]..vimwiki#vars#get_global:
line    1:
E716: Key not present in Dictionary: custom_wiki2html_args
E15: Invalid expression: g:vimwiki_global_vars[a:key]
E716: Key not present in Dictionary: custom_wiki2html_args
E15: Invalid expression: g:vimwiki_global_vars[a:key]
```

Something like this, it's not using vimwiki_markdown, but the error is similar.

**Comment by patrickdavey** [comment]
Those E716 etc. errors are coming from vimwiki (and vim) not from the gem. So, unless I'm missing something, there's something wrong with your vim setup. I haven't updated vimwiki in a while, so, possibly there's an error there.

If you can install with RVM (which takes care of these dependencies) then, I'm tempted to close this issue as I'm not sure what else I can do?

**Comment by patrickdavey** [comment]
Excellent idea - I've updated the README to suggest using RVM -> https://github.com/patrickdavey/vimwiki_markdown/commit/9cb738a493c0e68024a5e68a8699c83c14350b76

As for vimwiki errors... I'd imagine it's just a configuration issue? Do you have a link to the issue.

If you're happy for this to be closed `and the convert seems success` then please close it. I don't think there's much I can do (other than upgrade the gem dependency...) if you want to open a PR updating `libgit2` then I'll be happy to take a look and make sure the specs pass etc. Otherwise, happy to just have this closed :)

**Comment by PetrusZ** [comment]
Found the error come from vimwiki, which is missing `custom_wiki2html_args` defualt key and value. Close the issue.
